Force using the same utf8parse everywhere
prevent cargo vendor conflict:
```
cargo vendor
error: failed to sync

Caused by:
  found duplicate version of package `utf8parse v0.2.1` vendored from two sources:

  	source 1: registry `crates-io`
  	source 2: https://github.com/ayosec/vte-graphics.git?branch=graphics#8caae0d3
```